"""Agent discovery and classification constants.

`AGENT_RULES` is the canonical list of supported agent targets for extraction.
Each key can be used as `python -m extraction.run --target <agent>`.
"""

# GitHub search fragments keyed by agent name. These keys also define valid
# single-agent CLI targets. Use lowercase stable identifiers because they become
# local output group folder names.
AGENT_RULES = {
    # Devin bot commits or branches.
    "devin": ['author:"devin-ai-integration[bot]"', "head:devin/"],
    # Jules bot commits.
    "jules": ['author:"google-labs-jules[bot]"'],
    # Codex branches.
    "codex": ["head:codex/"],
    # Claude-authored work via branch prefix or attribution text.
    "claude": [
        "head:claude/",
        "author:claude[bot]",
        '"Co-Authored-By: Claude" in:body',
        '"Co-Authored-By: Claude" in:comments',
        '"Generated with Claude Code" in:body',
        '"Generated with Claude Code" in:comments',
    ],
    # GitHub Copilot branches.
    "copilot": ["head:copilot/"],
    # Cursor agent branches.
    "cursor": ["head:cursor/"],
    # JetBrains Junie bots (standard and EAP).
    "junie": ['author:"jetbrains-junie[bot]"', 'author:"junie-eap[bot]"'],
    # Codegen authored PRs or attribution text (issue search supports body/comments).
    "codegen": ["author:codegen-sh", '"About Codegen" in:body', '"About Codegen" in:comments'],
    # Cosine Genie branches.
    "cosine": ["head:cosine/"],
    # OpenHands branches or attribution (PR author or body/comments).
    "openhands": [
        "head:openhands",
        "author:openhands",
        "author:openhands-agent",
        '"Co-authored-by: openhands" in:body',
        '"Co-authored-by: openhands" in:comments',
        '"Automatic fix generated by OpenHands" in:body',
        '"Automatic fix generated by OpenHands" in:comments',
    ],
}

# First-commit author signatures for commit-based discovery/classification.
# These are separate from `AGENT_RULES` because commit search is a REST backfill:
# it catches PRs where the PR author/body/branch does not identify the agent,
# but the first commit author does. For a single-agent target, only the matching
# entry below is used.
FIRST_COMMIT_AUTHORS = {
    "openhands": ["openhands-agent"],
    "jules": ["google-labs-jules[bot]"],
    "claude": ["claude[bot]"],
}
