"""Human-target sampling and exclusion constants.

The human target is a counterfactual sample: PRs should have no known agentic
signals before enrichment, and they are checked again after enrichment. These
constants define the additional search exclusions and the post-enrichment
language quota used by `HumanSampler` and `HumanFilter`.
"""

# Additional agent-related GitHub search fragments excluded from human discovery.
#
# Keep these clauses for signals that should *not* become first-class agent
# targets in `AGENT_RULES`, but should still be filtered out of human sampling.
EXTRA_EXCLUDE_CLAUSES = [
    # Gru
    'author:"gru-agent[bot]"',
    # Cline
    '("Cline") OR ("cline.bot") OR ("reviewed by Cline") OR ("generated by Cline")',
    # SWE-agent
    "(head:open-swe/)",
    # Tembo
    'author:"tembo-io"',
    "(head:tembo/)",
    # Amazon Q Developer
    'author:"amazon-q-developer[bot]"',
    "(head:Q-DEV)",
]

# Target number of retained human PRs per allowed language after enrichment.
# The sampler may discover more candidates because post-enrichment filters can
# drop PRs that reveal agentic authorship or disallowed file languages.
TARGET_HUMAN_PRS_PER_LANGUAGE = 125000

# Allowed primary PR languages for the human target. Values are matched after
# enrichment from changed file extensions and should use the labels emitted by
# `extraction.utility.language_labeller`.
ALLOWED_PR_LANGUAGES = [
    "Python",
    "Java",
    "JavaScript",
    "C++",
]
