"""Analysis-side code smell standardization configuration."""

from __future__ import annotations

import re

# Exact raw rule/message labels that should map directly to a standardized smell type.
CODE_SMELL_RULE_MAP: dict[str, str] = {
    # DesigniteJava architectural smells
    "unstable dependency": "Unstable Dependency",
    "god component": "God Component",
    "feature concentration": "Feature Concentration",
    "dense structure": "Dense Structure",
    # DesigniteJava / DesignitePy design smells
    "multifaceted abstraction": "Multifaceted Abstraction",
    "feature envy": "Feature Envy",
    "deficient encapsulation": "Deficient Encapsulation",
    "insufficient modularization": "Insufficient Modularization",
    "broken modularization": "Broken Modularization",
    "hub like modularization": "Hub-like Modularization",
    "wide hierarchy": "Wide Hierarchy",
    "deep hierarchy": "Deep Hierarchy",
    "rebellious hierarchy": "Rebellious Hierarchy",
    "broken hierarchy": "Broken Hierarchy",
    # DesigniteJava implementation smells
    "complex conditional": "Complex Conditional",
    "complex method": "Complex Method",
    "empty catch clause": "Empty Catch Clause",
    "empty catch block": "Empty Catch Clause",
    "long identifier": "Long Identifier",
    "long method": "Long Method",
    "long parameter list": "Long Parameter List",
    "long statement": "Long Statement",
    "magic number": "Magic Number",
    "missing default": "Missing Default",
    "long lambda function": "Long Lambda Function",
    "long message chain": "Long Message Chain",
    # DesigniteJava machine learning smells
    "ambiguous merge key": "Ambiguous Merge Key",
    "broken nan check": "Broken NaN Check",
    "chain indexing": "Chain Indexing",
    "forward bypass": "Forward Bypass",
    "type blind conversion": "Type Blind Conversion",
    "unnecessary iteration": "Unnecessary Iteration",
    # DesignitePy architectural smells
    "cyclic dependency": "Cyclic Dependency",
    "ambiguous interface": "Ambiguous Interface",
    "scattered functionality": "Scattered Functionality",
    # DesignitePy design smells
    "imperative abstraction": "Imperative Abstraction",
    "unnecessary abstraction": "Unnecessary Abstraction",
    "unutilized abstraction": "Unutilized Abstraction",
    "unexploited encapsulation": "Unexploited Encapsulation",
    "cyclically dependent modularization": "Cyclically-Dependent Modularization",
    "multipath hierarchy": "Multipath Hierarchy",
    "cyclic hierarchy": "Cyclic Hierarchy",
    "missing hierarchy": "Missing Hierarchy",
    # DesignitePy implementation smells
    "abstract function call from constructor": "Abstract Function Call From Constructor",
    # DesignitePy testability smells
    "hard wired dependencies": "Hard-wired Dependencies",
    "hard wired dependency": "Hard-wired Dependencies",
    "global state": "Global State",
    "excessive dependency": "Excessive Dependency",
    "law of demeter violation": "Law of Demeter Violation",
    # DesignitePy test smells
    "assertion roulette": "Assertion Roulette",
    "missing assertion": "Missing Assertion",
    "conditional test logic": "Conditional Test Logic",
    "constructor initialization": "Constructor Initialization",
    "eager test": "Eager Test",
    "empty test": "Empty Test",
    "exception handling": "Exception Handling",
    "exceptional handling": "Exception Handling",
    "ignored test": "Ignored Test",
    "unknown test": "Unknown Test",
    # ESLint / SonarJS rule mappings
    "max lines per function": "Long Method",
    "max statements": "Too Many Responsibilities",
    "complexity": "Complex Conditional",
    "sonarjs cognitive complexity": "Long Method",
    "cognitive complexity": "Long Method",
    "max lines": "Overly Long File",
    "max classes per file": "Too Many Responsibilities",
    "max depth": "Deep Nesting",
    "max nested callbacks": "Callback Hell",
    "sonarjs no collapsible if": "Deep Nesting",
    "no collapsible if": "Redundant Code",
    "no nested ternary": "Complex Conditional",
    "duplicatecondition": "Repeated Conditions",
    "sonarjs no identical conditions": "Repeated Conditions",
    "sonarjs no duplicated branches": "Duplicate Code",
    "no duplicated branches": "Duplicate Code",
    "sonarjs no identical functions": "Duplicate Code",
    "no identical functions": "Duplicate Code",
    "sonarjs no duplicate string": "Duplicate Code",
    "no duplicate string": "Duplicate Code",
    "no duplicate imports": "Duplicate Code",
    "sonarjs max switch cases": "Switch Statements Too Large",
    "max switch cases": "Large Switch Statement",
    "sonarjs no small switch": "Switch Statements Too Large",
    "no small switch": "Speculative Generality",
    "no unused vars": "Dead Code",
    "no unreachable": "Dead Code",
    "no unused expressions": "Dead Code",
    "sonarjs no unused collection": "Unused Collections Or Values",
    "no unused collection": "Dead Code",
    "no magic numbers": "Magic Number",
    "no empty function": "Lazy Class / Empty Abstraction",
    "no empty static block": "Lazy Class / Empty Abstraction",
    "no empty": "Exception Swallowing",
    "max params": "Data Clumps / Too Many Parameters",
    "consistent return": "Inconsistent Behavior",
    "default case": "Inconsistent Behavior",
    "eqeqeq": "Suspicious Equality / Hidden Bugs",
    "no useless concat": "Redundant Code",
    "no useless return": "Redundant Code",
    "no extra boolean cast": "Redundant Code",
    "sonarjs no redundant boolean": "Redundant Code",
    "no redundant boolean": "Redundant Code",
    "sonarjs no redundant jump": "Redundant Code",
    "no redundant jump": "Lazy / Redundant Statements",
    "no unused private class members": "Temporary Field / Unused State",
    "class methods use this": "Feature Envy",
    "no param reassign": "Mutable Shared State",
    "prefer const": "Mutable Shared State",
    "use isnan": "Suspicious Equality / Hidden Bugs",
    "no self compare": "Suspicious Equality / Hidden Bugs",
    "no lonely if": "Unnecessary Complexity",
    "no dupe else if": "Repeated Conditions",
    "sonarjs no inverted boolean check": "Boolean Blindness / Confusing Booleans",
    "no inverted boolean check": "Confusing Conditional",
    "sonarjs no gratuitous expressions": "Obscure Intent",
    "no gratuitous expressions": "Obscure Intent",
    "sonarjs no one iteration loop": "One-Iteration Loops",
    "no one iteration loop": "One-Iteration Loops",
    "no useless catch": "Empty Catch Clause",
    "bugprone empty catch": "Empty Catch Clause",
    "no else return": "Redundant Control Flow",
    "sonarjs no ignored return": "Unused Collections Or Values",
    "no eval": "Unsafe Dynamic Code",
    "no implied eval": "Unsafe Dynamic Code",
    "no new func": "Unsafe Dynamic Code",
    "no global assign": "Global State Abuse",
    "no implicit globals": "Global State Abuse",
    "no undef": "Global State Abuse",
    # Additional SonarJS / ESLint rules from extended mapping
    "elseif without else": "Incomplete Conditional Logic",
    "no collection size mischeck": "Conditional Complexity",
    "no nested switch": "Spaghetti Code",
    "no nested template literals": "Obscure Intent",
    "no same line conditional": "Obscure Intent",
    "prefer immediate return": "Temporary Variable",
    "prefer object literal": "Primitive Obsession",
    "prefer single boolean return": "Verbose Conditional",
    "prefer while": "Overcomplicated Control Flow",
    # Cppcheck rule ids / output labels
    "complexcondition": "Complex Conditional",
    "duplicatebreak": "Redundant Control Flow",
    "redundantassignment": "Redundant Code",
    "identicalconditionafterearlyexit": "Duplicate Logic",
    "oppositeinnercondition": "Confusing Conditional",
    "incorrectlogicoperator": "Conditional Complexity",
    "clarifycondition": "Obscure Intent",
    "duplicateexpression": "Duplicate Code",
    "unreachablecode": "Dead Code",
    "redundantcondition": "Redundant Logic",
    "knownconditiontruefalse": "Dead Branches",
    "switchcasefallthrough": "Suspicious Control Flow",
    "duplicatebranch": "Duplicate Code",
    "unusedfunction": "Dead Code / Lazy Class",
    "unusedvariable": "Dead Code",
    "unusedstructmember": "Dead State",
    "unusedlabel": "Dead Code",
    "unreadvariable": "Write-only Variable",
    "assignedbutunusedvariable": "Temporary Variable",
    "variablescope": "Variable Scope Too Large",
    "constvariable": "Mutable State Smell",
    "redundantcopy": "Redundant State",
    "functionstatic": "Feature Envy",
    "passedbyvalue": "Primitive Obsession",
    "constparameter": "Mutable Shared State",
    "memleak": "Resource Leak",
    "resourceleak": "Resource Leak",
    "doublefree": "Unsafe Resource Handling",
    "mismatchallocdealloc": "Inconsistent Resource Management",
    "nullpointer": "Unsafe State Handling",
    "danglinglifetime": "Temporal Coupling",
    "invalidlifetime": "Lifetime Mismanagement",
    "returndanglinglifetime": "Escaping Temporary",
    "accessmoved": "Invalid Object State",
    "deallocuse": "Use After Free",
    "stloutofbounds": "Collection Misuse",
    "uninitmembervar": "Temporary Field",
    "uninitializedvariable": "Undefined State",
    "uninitstructmember": "Incomplete Initialization",
    # Cppcheck phrase / message pattern labels
    "deeply nested if chains": "Spaghetti Code",
    "nested loops": "Excessive Nesting",
    "duplicate code fragments": "Duplicate Code",
    "repeated conditions": "Duplicate Logic",
    "repeated assignments": "Redundant Code",
    "identical branches": "Duplicate Branches",
    "repeated stl operations": "Duplicate Abstraction",
    "excessive public members": "Data Class",
    "missing virtual destructor": "Refused Bequest",
    "unused private function": "Lazy Class",
    "class with only data": "Data Class",
    "too many parameters": "Long Parameter List",
    "global variable warnings": "Global Data",
    "improper inheritance use": "Refused Bequest",
    "invalid iterator usage": "Collection Misuse",
    "dereferencing invalid iterator": "Unsafe Collection Handling",
    "inefficient stl iteration": "Inefficient Abstraction",
    "unnecessary copying in loops": "Performance Bottleneck",
    "use of size in loop repeatedly": "Inefficient Loop",
    "inefficient vector resizing": "Performance Smell",
    "incorrect container access": "Inappropriate Intimacy with Container",
    "constructor missing initialization": "Temporary Field",
    "partially initialized object": "Inconsistent State",
    "missing member initialization list": "Poor Construction",
    "c style cast": "Primitive Obsession",
    "dangerous cast": "Unsafe Type Conversion",
    "implicit conversion": "Hidden Behavior",
    "ignored return value": "Incomplete Error Handling",
    "exception not caught": "Poor Exception Handling",
    "throwing raw pointers": "Primitive Obsession",
    "passing large object by value": "Inefficient Data Handling",
    "unnecessary copy constructor calls": "Excessive Copying",
    "inefficient string concatenation": "Inefficient Abstraction",
    "post increment instead of pre increment": "Minor Inefficiency",
    "expensive function call in loop": "Loop Inefficiency",
    "redundant temporary object": "Temporary Object",
    "use of endl excessively": "IO Performance Smell",
    "overly long expressions": "Obscure Intent",
    "magic numbers": "Primitive Obsession",
    "boolean complexity": "Complex Conditional",
    "excessive pointer arithmetic": "Low-Level Obsession",
    "macro overuse": "Preprocessor Abuse",
    "deeply nested ternaries": "Obscure Intent",
    # clang-tidy checks
    "readability-function-cognitive-complexity": "Long Method",
    "bugprone-branch-clone": "Duplicate Branches",
    "bugprone-redundant-branch-condition": "Redundant Conditional Logic",
    "readability-else-after-return": "Redundant Control Flow",
    "misc-redundant-expression": "Redundant Logic",
    "bugprone-infinite-loop": "Faulty Control Flow",
    "bugprone-suspicious-semicolon": "Suspicious Control Flow",
    "bugprone-too-small-loop-variable": "Loop Logic Smell",
    "modernize-loop-convert": "Overcomplicated Looping",
    "readability-isolate-declaration": "Obscure Control Flow",
    "modernize-use-equals-default": "Boilerplate Code",
    "modernize-use-equals-delete": "Boilerplate Code",
    "readability-redundant-control-flow": "Redundant Statements",
    "clang-analyzer-deadcode.deadstores": "Dead Store / Dead Code",
    "misc-unused-parameters": "Dead Parameter",
    "misc-unused-alias-decls": "Dead Abstraction",
    "misc-unused-using-decls": "Dead Code",
    "bugprone-unused-return-value": "Ignored Behavior",
    "readability-container-size-empty": "Redundant Code",
    "bugprone-use-after-move": "Invalid Object State",
    "bugprone-dangling-handle": "Dangling Reference",
    "danglingtemporarylifetime": "Dangling Reference",
    "bugprone-move-forwarding-reference": "Ownership Mismanagement",
    "clang-analyzer-cplusplus.newdeleteleaks": "Resource Leak",
    "clang-analyzer-unix.malloc": "Memory Leak",
    "cppcoreguidelines-owning-memory": "Unsafe Ownership",
    "modernize-make-unique": "Manual Resource Management",
    "modernize-make-shared": "Manual Resource Management",
    "cppcoreguidelines-no-malloc": "Unsafe Memory Management",
    "readability-redundant-member-init": "Redundant Initialization",
    "cppcoreguidelines-special-member-functions": "Incomplete Object Semantics",
    "modernize-use-override": "Fragile Inheritance",
    "cppcoreguidelines-virtual-class-destructor": "Refused Bequest",
    "bugprone-parent-virtual-call": "Inheritance Misuse",
    "cppcoreguidelines-pro-type-member-init": "Temporary Field",
    "virtualcallinconstructor": "Abstract Function Call From Constructor",
    "cppcoreguidelines-avoid-non-const-global-variables": "Global Data",
    "misc-no-recursion": "Excessive Coupling / Recursive Complexity",
    "misc header include cycle": "Cyclic Dependency",
    "cppcoreguidelines-interfaces-global-init": "Global Initialization Dependency",
    "readability-convert-member-functions-to-static": "Feature Envy",
    "modernize-use-bool-literals": "Primitive Obsession",
    "modernize-avoid-c-arrays": "Primitive Obsession",
    "modernize-pass-by-value": "Inefficient Data Passing",
    "modernize-raw-string-literal": "Escaping Complexity",
    "modernize-shrink-to-fit": "Resource Waste",
    "modernize-use-emplace": "Inefficient Construction",
    "modernize-use-default-member-init": "Temporary Field",
    "modernize-macro-to-enum": "Macro Abuse",
    "performance-for-range-copy": "Excessive Copying",
    "performance-inefficient-string-concatenation": "Inefficient Abstraction",
    "performance-inefficient-vector-operation": "Collection Misuse",
    "performance-move-const-arg": "Ineffective Move Semantics",
    "performance-no-automatic-move": "Missed Move Optimization",
    "performance-unnecessary-copy-initialization": "Redundant Copying",
    "performance-unnecessary-value-param": "Pass-by-Value Smell",
    "performance-faster-string-find": "Inefficient Search",
    "performance-enum-size": "Oversized Representation",
    "readability-implicit-bool-conversion": "Hidden Semantics",
    "readability-magic-numbers": "Magic Number",
    "readability-suspicious-call-argument": "Confusing API Usage",
    "readability-braces-around-statements": "Ambiguous Control Flow",
    "readability-qualified-auto": "Obscure Type Semantics",
    "readability-string-compare": "Unsafe String Logic",
    "readability-uniqueptr-delete-release": "Ownership Confusion",
    "readability-use-anyofallof": "Verbose Logic",
    "bugprone-assert-side-effect": "Hidden Side Effects",
    "bugprone-copy-constructor-init": "Incorrect Initialization",
    "bugprone-exception-escape": "Unsafe Exception Flow",
    "bugprone-forwarding-reference-overload": "Ambiguous API Design",
    "bugprone-inaccurate-erase": "Incorrect Collection Usage",
    "bugprone-macro-parentheses": "Macro Abuse",
    "bugprone-misplaced-widening-cast": "Unsafe Type Conversion",
    "bugprone-narrowing-conversions": "Unsafe Conversion",
    "bugprone-sizeof-expression": "Incorrect Memory Semantics",
    "bugprone-string-integer-assignment": "Primitive Misuse",
    "bugprone-suspicious-string-compare": "Incorrect String Logic",
    "bugprone-swapped-arguments": "Confusing API Calls",
    "bugprone-unhandled-self-assignment": "Fragile Assignment Semantics",
    "bugprone-undefined-memory-manipulation": "Unsafe Memory Operations",
}

# Generic raw labels that should not be used as standardized smell types without
# consulting message/category context.
GENERIC_CODE_SMELL_RULE_IDS: set[str] = {
    "eslint",
    "designite_smell",
    "designite smell",
    "maintainability_smell",
    "maintainability smell",
    "parsing error",
}

# Message substring overrides used when a raw rule id is too generic.
CODE_SMELL_MESSAGE_CONTAINS_MAP: dict[str, str] = {
    "unexpected token": "Parsing Error",
    "deeply nested if": "Spaghetti Code",
    "nested loop": "Excessive Nesting",
    "missing virtual destructor": "Refused Bequest",
    "global variable": "Global Data",
    "invalid iterator": "Collection Misuse",
    "dereferencing invalid iterator": "Unsafe Collection Handling",
    "member initialization list": "Poor Construction",
    "c-style cast": "Primitive Obsession",
    "deprecated api": "Obsolete Abstraction",
    "ignored return value": "Incomplete Error Handling",
    "exception not caught": "Poor Exception Handling",
    "large object by value": "Inefficient Data Handling",
    "string concatenation": "Inefficient Abstraction",
    "pointer arithmetic": "Low-Level Obsession",
    "macro overuse": "Preprocessor Abuse",
}


def _canonical_code_smell_lookup_key(value: str | None) -> str:
    text = str(value or "").strip()
    text = re.sub(r"[_\-./:]+", " ", text)
    text = re.sub(r"[^A-Za-z0-9]+", " ", text)
    return " ".join(text.lower().split())


NORMALIZED_CODE_SMELL_RULE_MAP: dict[str, str] = {
    _canonical_code_smell_lookup_key(raw_label): standardized_label
    for raw_label, standardized_label in CODE_SMELL_RULE_MAP.items()
    if _canonical_code_smell_lookup_key(raw_label)
}

NORMALIZED_CANONICAL_CODE_SMELL_LABELS: dict[str, str] = {
    _canonical_code_smell_lookup_key(standardized_label): standardized_label
    for standardized_label in CODE_SMELL_RULE_MAP.values()
    if _canonical_code_smell_lookup_key(standardized_label)
}

NORMALIZED_GENERIC_CODE_SMELL_RULE_IDS: set[str] = {
    _canonical_code_smell_lookup_key(raw_label)
    for raw_label in GENERIC_CODE_SMELL_RULE_IDS
    if _canonical_code_smell_lookup_key(raw_label)
}

NORMALIZED_CODE_SMELL_MESSAGE_CONTAINS_MAP: dict[str, str] = {
    _canonical_code_smell_lookup_key(needle): standardized_label
    for needle, standardized_label in CODE_SMELL_MESSAGE_CONTAINS_MAP.items()
    if _canonical_code_smell_lookup_key(needle)
}


def canonicalize_code_smell_type(
    *,
    rule_id: str | None,
    category: str | None,
    message: str | None,
    tool: str | None,
) -> str | None:
    raw_rule = str(rule_id or "").strip()
    normalized_rule = _canonical_code_smell_lookup_key(raw_rule)
    if normalized_rule in NORMALIZED_CODE_SMELL_RULE_MAP:
        return str(NORMALIZED_CODE_SMELL_RULE_MAP[normalized_rule]).strip()
    if normalized_rule in NORMALIZED_CANONICAL_CODE_SMELL_LABELS:
        return str(NORMALIZED_CANONICAL_CODE_SMELL_LABELS[normalized_rule]).strip()
    lowered_message = _canonical_code_smell_lookup_key(message)
    for needle, standardized_label in NORMALIZED_CODE_SMELL_MESSAGE_CONTAINS_MAP.items():
        if needle and needle in lowered_message:
            return str(standardized_label).strip()
    return None
